#!/usr/bin/env python
# coding: utf-8
from __future__ import print_function, division, unicode_literals, absolute_import

import sys
import os
import time
import mkdocs.__main__

# We don't install with setup.py hence we have to add the directory [...]/abinit/tests to $PYTHONPATH
pack_dir = os.path.dirname(__file__)
sys.path.insert(0, pack_dir)

# This needed to import doc.tests
sys.path.insert(0, os.path.join(pack_dir, "doc"))


def main():
    verbose = 1 if "-v" in sys.argv or "--verbose" in sys.argv else 0
    if "--help" in sys.argv or "-h" in sys.argv:
        return mkdocs.__main__.cli()

    from pymods.website import build_website
    if len(sys.argv) > 1 and ("--help" not in sys.argv or "-h" not in sys.argv):
        start = time.time()
        website = build_website("./doc", verbose=verbose)
        print("Initial website generation completed in %.2f [s]" % (time.time() - start))

    if len(sys.argv) > 1 and sys.argv[1] == "validate":
        print("Validating website build")
        return website.validate_html_build()

    if len(sys.argv) > 1 and sys.argv[1] in ("build", "serve", "gh-deploy"):
        start = time.time()
        website.generate_markdown_files()
        print("Markdown files generation completed in %.2f [s]" % (time.time() - start))
        print(website)

    if "--dry-run" in sys.argv: return 0
    return mkdocs.__main__.cli()


if __name__ == '__main__':
    sys.exit(main())