site_name: abinit
site_url: http://www.abinit.org
site_description: Abinit documentation
site_author: The Abinit group
docs_dir: doc

repo_url: https://github.com/abinit/abinit/

pages:
- Quick Start: 
    - Introduction: index.md
    - Installation:  installation.md
    - Topics:
        - Crystalline Structure: topics/crystal.md
        - K-points: topics/kpoints.md
- User Guide:
    - Overview: user-guide/help_what_ABINIT_does.md
    - Abinit: user-guide/help_abinit.md
    - Mrgddb: user-guide/help_mrgddb.md
    - Optic: user-guide/help_optic.md
- Input Variables:
    - Abinit:
        - All Variables: input_variables/varlist_abinit.md
        - Basic: input_variables/varbas.md
        - Bethe-Salpeter: input_variables/varbse.md
        - Developers: input_variables/vardev.md
        - DMFT: input_variables/vardmft.md
        - Electron-Phonon: input_variables/vareph.md
        - Varff: input_variables/varff.md
        - File-handling: input_variables/varfil.md
        - Geometry: input_variables/vargeo.md
        - Ground-State: input_variables/vargs.md
        - GW: input_variables/vargw.md
        - Internal: input_variables/varint.md
        - Parallelism: input_variables/varpar.md
        - PAW: input_variables/varpaw.md
        - RF: input_variables/varrf.md
        - Relaxation: input_variables/varrlx.md
        - VdW: input_variables/varvdw.md
        - Wannier90: input_variables/varw90.md
- Tutorials:
    - Overview: tutorials/welcome.md
    - Base Tutorials: 
        - Base1: tutorials/base1.md
        - Base2: tutorials/base2.md
        - Base3: tutorials/base3.md
        - Base4: tutorials/base4.md
    - DFPT:
        - RF1: tutorials/rf1.md
        - RF2: tutorials/rf2.md
        - Elastic: tutorials/elastic.md
        - EPH: tutorials/eph.md
    - DMFT: tutorials/dmft.md
    - Many-Body:
        - GW1: tutorials/gw1.md
        - GW2: tutorials/gw2.md
        - Bethe-Salpeter: tutorials/bse.md
    - Parallelism:
        - Base: tutorials/basepar.md
        - Many-Body: tutorials/paral_mbt.md
- Theory:
    - MBPT: theory/theory_mbt.md
    - Additional Material: theory/additional_material.md
    - Bibliography: bibliography.md
- About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

markdown_extensions:
  - markdown.extensions.toc:
     permalink: true
     #separator: "_"
  - markdown.extensions.admonition
  - markdown.extensions.fenced_code 
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.smarty
  #- markdown_newtab
  #- markdown.extensions.wikilinks
  - pymods.extensions.wikilinks:
  - pymods.extensions.modal:
  - mdx_math:
        enable_dollar_delimiter: True
        
#strict: true

copyright: Copyright &copy; 2017 The Abinit Group
#google_analytics: ['UA-27795084-5', 'abinit.org']
#

theme: mkdocs
#theme: readthedocs
#theme: material   # Nice
#theme: bootstrap
#theme: bootswatch
#theme: flatly
#theme: cinder
#theme: docSkimmer
#theme: windmill
#theme: journal
#theme: yeti
#theme: united
#theme: spacelab
#theme: docSkimmer
theme_dir: abinit_theme
extra_css:
    - css/extra.css
    - css/codehilite.css

extra_javascript:
    - extra_javascript/github_edit.js
#extra_javascript: 
    #- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    #- http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
    version: 8.5.4
    # For Material them
    #logo: 'images/logo.svg
    #feature:
    #    tabs: true
