site_name: abinit
site_url: http://www.abinit.org
site_description: Abinit documentation
site_author: The Abinit group
docs_dir: doc

repo_url: https://github.com/abinit/abinit/

pages:
- Quick Start: 
    - Introduction: index.md
    - Installation:  installation.md
- User Guide:
    - Overview: user-guide/help_what_ABINIT_does.md
    - Abinit: user-guide/help_abinit.md
    - Mrgddb: user-guide/help_mrgddb.md
    - Optic: user-guide/help_optic.md
- Topics:
    - topics/Artificial.md
    - topics/AtomManipulator.md
    - topics/AtomTypes.md
    - topics/Bader.md
    - topics/BandOcc.md
    - topics/Berry.md
    - topics/BSE.md
    - topics/ConstrainedPol.md
    - topics/Control.md
    - topics/Coulomb.md
    - topics/CRPA.md
    - topics/crystal.md
    - topics/Dev.md
    - topics/DFPT.md
    - topics/DFT+U.md
    - topics/DMFT.md
    - topics/EffMass.md
    - topics/EFG.md
    - topics/Elastic.md
    - topics/ElecBandStructure.md
    - topics/ElecDOS.md
    - topics/ElPhonInt.md
    - topics/ElPhonTransport.md
    - topics/ForcesStresses.md
    - topics/FrequencyMeshMBPT.md
    - topics/GeoConstraints.md
    - topics/GeoOpt.md
    - topics/GW.md
    - topics/GWls.md
    - topics/Hybrids.md
    - topics/index.md
    - topics/k-points.md
    - topics/LOTF.md
    - topics/MagField.md
    - topics/MagMom.md
    - topics/MolecularDynamics.md
    - topics/multidtset.md
    - topics/nonlinear.md
    - topics/Optic.md
    - topics/Output.md
    - topics/parallelism.md
    - topics/PAW.md
    - topics/PhononBands.md
    - topics/Phonons.md
    - topics/PhononWidth.md
    - topics/PIMD.md
    - topics/Planewaves.md
    - topics/positron.md
    - topics/printing.md
    - topics/PseudosPAW.md
    - topics/q-points.md
    - topics/RandStopPow.md
    - topics/Recursion.md
    - topics/RPACorrEn.md
    - topics/SCFAlgorithms.md
    - topics/SCFControl.md
    - topics/SelfEnergy.md
    - topics/SmartSymm.md
    - topics/spinpolarisation.md
    - topics/STM.md
    - topics/Susceptibility.md
    - topics/TDDFT.md
    - topics/TDepES.md
    - topics/Temperature.md
    - topics/TransPath.md
    - topics/TuningSpeed.md
    - topics/UnitCell.md
    - topics/vdw.md
    - topics/Wannier.md
    - topics/Wavelets.md
    - topics/xc.md
- Input Variables:
    - Abinit:
        - All Variables: input_variables/varlist_abinit.md
        - Basic: input_variables/basic.md
        - Bethe-Salpeter: input_variables/bse.md
        - Developers: input_variables/dev.md
        - DMFT: input_variables/dmft.md
        - Electron-Phonon: input_variables/eph.md
        - Varff: input_variables/ffield.md
        - File-handling: input_variables/files.md
        - Geometry: input_variables/geo.md
        - Ground-State: input_variables/gstate.md
        - GW: input_variables/gw.md
        - Internal: input_variables/internal.md
        - Parallelism: input_variables/paral.md
        - PAW: input_variables/paw.md
        - DFPT: input_variables/dfpt.md
        - Relaxation: input_variables/rlx.md
        - VdW: input_variables/vdw.md
        - Wannier90: input_variables/w90.md
    - Anaddb: input_variables/anaddb.md
    - Optic: input_variables/optic.md
    - Aim: input_variables/aim.md
    - Statistics: input_variables/varset_stats.md
- Lessons:
    - Overview: tutorials/welcome.md
    - Base Tutorials: 
        - Base1: tutorials/base1.md
        - Base2: tutorials/base2.md
        - Base3: tutorials/base3.md
        - Base4: tutorials/base4.md
    - DFPT:
        - RF1: tutorials/rf1.md
        - RF2: tutorials/rf2.md
        - Elastic: tutorials/elastic.md
        - EPH: tutorials/eph.md
    - DMFT: tutorials/dmft.md
    - Many-Body:
        - GW1: tutorials/gw1.md
        - GW2: tutorials/gw2.md
        - Bethe-Salpeter: tutorials/bse.md
    - Parallelism:
        - Base: tutorials/basepar.md
        - Many-Body: tutorials/paral_mbt.md
- Theory:
    - MBPT: theory/theory_mbt.md
    - Additional Material: theory/additional_material.md
    - Bibliography: bibliography.md
- Developers:
    - How to write docs: developers/README.md
- About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

markdown_extensions:
  - markdown.extensions.meta
  - markdown.extensions.toc:
        permalink: true
     #separator: "_"
  - markdown.extensions.admonition
  # - markdown.extensions.fenced_code 
  # - markdown.extensions.codehilite
  # - markdown.extensions.def_list
  # - markdown.extensions.smarty
  # - markdown.extensions.tables
  #- markdown_newtab
  - mdx_math:
        enable_dollar_delimiter: True
  # Abinit extensions.
  - pymods.extensions.wikilinks:
  - pymods.extensions.modal:
        
#strict: true

copyright: Copyright &copy; 2017 The Abinit Group
#google_analytics: ['UA-27795084-5', 'abinit.org']

#theme: mkdocs
#theme: readthedocs
theme: material   # Nice
#theme: bootstrap
#theme: flatly
#theme: cinder
#theme: docSkimmer
#theme: windmill
#theme: journal
#theme: united
#theme: simplex
#theme: yeti
#theme: spacelab
#theme: docSkimmer
theme_dir: abinit_theme

extra_css:
    - css/codehilite.css
    - css/extra.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.8/ace.js
    #- https://cdn.plot.ly/plotly-latest.min.js
    - extra_javascript/abidocs.js

extra:
    version: 8.5.4
    # For Material them
    #logo: "images/logo.svg"
    feature:
        tabs: true
